### ISSUE TITLE
CreateAzureServicesScript.ps1 issues

### ISSUE THREAD

**Issue by tdjastrzebski** [Microsoft/AzureUsageAndBillingPortal#17]
It seems that currently the only supported location is "Central US".
If any other location is specified "Application Insights" setup will error out.

In the last script part AzureWebJobsDashboard and AzureWebJobsStorage AccountKeys do not show up.

**Comment by mustafakasap** [comment]
Powershell script updated, please check the latest version to get Account Keys.

**Comment by Mike-Honey** [comment]
Yeah that would be helpful, except you seem to have ignored the Resouce typos, so if you test it you would find it produces errors.

**Comment by russelldyas** [comment]
@tdjastrzebski 

There is pull request from myself to make that clear in comments.  As currently Application Insights is only available in Central US.

Russell

**Comment by mustafakasap** [comment]
Typo in variable name will not cause any error to run the script. So it is not true to say the script didnt run because of typo. Please check the video (https://channel9.msdn.com/blogs/Mustafa-Kasap/How-to-Setup-the-Azure-Usage--Billing-Portal) which shows every single piece of installation steps with the current repo files. A brand new OS installation is used (without any modification or third party app installation etc) while recording this video.

**Comment by mustafakasap** [comment]
Typos fixed, Restriction to Central US is removed. Now you can specify other supported locations. As Insights is just supported under Central US, for now just his part is created under Central US (hard coded in Json template)
