### ISSUE TITLE
Error: DisallowedProvider - The operation is not permitted for namespace 'Microsoft.Commerce'

### ISSUE THREAD

**Issue by FBoucher** [Microsoft/AzureUsageAndBillingPortal#36]
Hi,
I installed Aubi and it works fine. However, if I add a subscription coming from the Partner Center or from 
CSP (Cloud Solution Provider), I got error 
When the webjob is executing `GetRateCardInfo`, I got an Error.

> "error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.Commerce'

Any workaround? hint? soluiton?

Thanks.

**Comment by TVDKoni** [comment]
I have same issue. Did you found a solution?

**Comment by FBoucher** [comment]
yes, but it's not a quickfix.
I have a solution running, but need some time to integrate it in Aubi. I will try to make some progress and share it in a feature branch soon.

**Comment by boyan100** [comment]
Hi, 

Since it's not a quick fix to code, would you be able to explain the fix? I need to code that fix in an application of ours. 

Thank you very much!

**Comment by harleenkohli** [comment]
Hi all, sorry for jumping in unannounced on this thread. AFAIK - The reason behind this error is because CSP based subscriptions are black-listed from getting data directly from Rate Card APIs directly - and for good reason - this breaks the trust model between Microsoft -> CSP -> End Customer. The rate card in this case is for CSP's eyes only as they decide their own rates which will be charged to the customer.

@FBoucher Would be interested to understand the technical way to get around this problem :) Were you able to resolve it without using CREST or CSP PC APIs?

@boyan100 , @TVDKoni - We have developed another solution which is similar to AUBP, but it caters to CSP scenario explicitly by using Partner Centre APIs instead. Please check it out and see if it meets your business need: https://github.com/Microsoft/peek

**Comment by boyan100** [comment]
Thanks Harleen!

I understand about the rate card and breaking the MS -> CSP -> CSP Customer trust.

We get that same exact error when trying to get usages (not rate cards): https://msdn.microsoft.com/en-us/library/azure/mt219001.aspx

Is this because usages and rate cards both go through Microsoft.Commerce and that whole provider is black listed in the API calls?

Thank you!

**Comment by harleenkohli** [comment]
@boyan100 - yes we also noted the same behavior during our tests with usage APIs - same error. I am not sure about the technical reasoning behind this though - but i think you have the right idea :)

**Comment by FBoucher** [comment]
Yes, I'm using the CSP PC APIs.
I finished my PoC, so I really know it's working.
I will create a branch and start importing that logic in Aubi.
But it will work only for a CSP owner, since you need Partner Center creds to get access to the data.

**Comment by FBoucher** [comment]
@harleenkohli thank you for introducing me to Peek (https://github.com/Microsoft/peek).  

I will not add support to CSP subscription in the AUbi portal since Peek exists and they have differents purpose.

If you are building a portal for your CSP subscription Peek is a great starting point. And you will find more detail on the API on the PartnerCenter   site.
