### ISSUE TITLE
AzureWebJobsDashboard and AzureWebJobsStorage doesnt show key

### ISSUE THREAD

**Issue by 5nowx** [Microsoft/AzureUsageAndBillingPortal#52]
In the version of azure Powershell 1.4 to get the specific key you need to append .Value[0] instead of .key1 like it says in line 156 and 158 of /Scripts/CreateAzureServicesScript.ps1 

The result is that AzureWebJobsDashboard and AzureWebJobsStorage ends after AzureWebJobsDashboard: DefaultEndpointsProtocol=https;AccountName=XXXXXX;AccountKey=

and after the change to value[0] appends the AccountKey Value.
it's solved but i want to let you know so if somebody has this problem it can solve it(or the change can be made to the script)

this is the resulting code:
`(Get-AzureRmStorageAccountKey -Name $StorageAccountName -ResourceGroupName $ResourceGroupName).Value[0]`

**Comment by GloveNinja217** [comment]
Hi there.

I've come across the same issue as you, and I changed the line to append .value[0] instead of .key1. I also changed the code from $storageKey = Get-AzureRmStorageAccountKey -Name $StorageAccountName -ResourceGroupName $ResourceGroupName 
to be this:
$storageKey = (Get-AzureRmStorageAccountKey -Name $StorageAccountName -ResourceGroupName $ResourceGroupName).value[0] like you mentioned.

For some reason I got a bunch of errors when I tried to do that. The output said it can't index into a null array. Did I do something wrong?

**Comment by 5nowx** [comment]
@GloveNinja217 
I make the change in the line 156 and 158. It's a line that changes the parameters that you then have to add to the Visual Solution.

i run this yesterday and got the correct output:

```
Write-Host ("DefaultEndpointsProtocol=https;AccountName=" + $StorageAccountName + ";AccountKey=" + $storageKey.value[0]) -foreground Red 



Write-Host ("DefaultEndpointsProtocol=https;AccountName=" + $StorageAccountName + ";AccountKey=" + $storageKey.value[0]) -foreground Red 

```

**Comment by mustafakasap** [comment]
This issue fixed.
